name: HakuaPay
main: jp.hakuaserver.hakuapay.HakuaPay
version: 1.5
api-version: 1.21
depend: [Vault, Citizens]
commands:
  hakuapay:
    aliases: [hkp]
    description: お金関連のコマンド
    usage: /hakuapay <add|set|check|send|reload> <player> <amount>
    permission: hakuapay.use
  job:
    description: 職業関連のコマンド
    usage: /job <add|remove|list|myjob|createnpc|deletenpc|addjob|gui>
    permission: job.use
  audio:
    description: オーディオ関連のコマンド
    permission: audio.use


permissions:
    hakuapay.admin:
        description: 管理者権限
        default: op
    hakuapay.user:
        description: ユーザー権限
        default: true
    hakuapay.addmoney:
      description: お金を追加する権限
      default: op
    hakuapay.setmoney:
      description: お金を設定する権限
      default: op
    hakuapay.checkmoney:
      description: 残高を確認する権限
      default: true
    hakuapay.sendmoney:
      description: お金を送金する権限
      default: true
    hakuapay.reload:
      description: プラグインをリロードする権限
      default: op
    job.use:
      description: 職業コマンドを使用する基本権限
      default: true
    job.add:
      description: 職業を追加する権限
      default: op
    job.remove:
      description: 職業を削除する権限
      default: op
    job.list:
      description: 職業一覧を表示する権限
      default: true
    job.myjob:
      description: 自分の職業を確認する権限
      default: true
    job.createnpc:
      description: 職業NPCを生成する権限
      default: op
    job.deletenpc:
      description: 職業NPCを削除する権限
      default: op
    hakuapay.addjob:
      description: 新しい職業を追加する権限
      default: op